### ISSUE TITLE
3주차 dfs 2023/2/5 (일)

### ISSUE THREAD

**Issue by tjwjdgks** [dk-algorithm/algorithm-study#13]
dfs 문제 링크 올려주세요

양식
[enzo] <문제 링크>

**Comment by BaekKunHee** [comment]
[han] https://school.programmers.co.kr/learn/courses/30/lessons/43165 타겟넘버

**Comment by changjun6518** [comment]
[준] 스도쿠 - https://www.acmicpc.net/problem/2580

**Comment by protossking** [comment]
[bear] DFS 와 BFS https://www.acmicpc.net/problem/1260

**Comment by ash753** [comment]
[henry] 맥주 마시면서 걸어가기 https://www.acmicpc.net/problem/9205

**Comment by choiyoungkwon12** [comment]
[ned] 단지번호붙이기 https://www.acmicpc.net/problem/2667

**Comment by tjwjdgks** [comment]
[enzo] 다단계 칫솔 판매 https://school.programmers.co.kr/learn/courses/30/lessons/77486

**Comment by JoongHyuk-Kim** [comment]
[sherlock] 게임 맵 최단거리 https://school.programmers.co.kr/learn/courses/30/lessons/1844

**Comment by tjwjdgks** [comment]
> [han] https://school.programmers.co.kr/learn/courses/30/lessons/43165 타겟넘버

좋은 문제 인것 같아요! dfs,bfs,dp, 비트마스킹, 완탐 다 할 수 있네요. 굿!
