### ISSUE TITLE
4주차 BFS 2023/2/12(일)

### ISSUE THREAD

**Issue by changjun6518** [dk-algorithm/algorithm-study#21]
bfs 문제 링크 올려주세요

양식
[enzo] <문제 링크>

**Comment by changjun6518** [comment]
왜 이 문제를 선택했나?

문제 푼 데 걸린 시간은?

시간 복잡도는 ? (잘 모르겠다면 예상)

문제 설명

문제 풀이 설명

**Comment by changjun6518** [comment]
[준] 미로탐색 - https://www.acmicpc.net/problem/2178

**Comment by changjun6518** [comment]
아이고 여기서 보이네요 ;
이전 PR에 커밋 올라가서 안보일줄알고 두번 올렸슴돠
아랫것은 무시해주세요!

**Comment by JoongHyuk-Kim** [comment]
[sherlock] - 유기농 배추 https://www.acmicpc.net/problem/1012 
저번주에 bfs를 올려서 이번주에는 dfs 문제 풀겠습니다!

**Comment by ash753** [comment]
[헨리] 경쟁적 전염 - https://www.acmicpc.net/problem/18405

**Comment by choiyoungkwon12** [comment]
[ned] 촌수 계산 - https://www.acmicpc.net/problem/2644

**Comment by protossking** [comment]
[bear] 안전영역 - https://www.acmicpc.net/problem/2468

**Comment by tjwjdgks** [comment]
[enzo] 서울 지하철 2호선 https://www.acmicpc.net/problem/16947

**Comment by BaekKunHee** [comment]
[han] 가장 먼 노드 https://school.programmers.co.kr/learn/courses/30/lessons/49189 

넘 늦게 올려서 죄송합니다
