### ISSUE TITLE
5주차 구현 2023/2/19(일)

### ISSUE THREAD

**Issue by changjun6518** [dk-algorithm/algorithm-study#29]

**Comment by changjun6518** [comment]
문제 링크 올려주세요

양식
[enzo] <문제 링크>

---
문제 설명

문제 풀이 설명

왜 이 문제를 선택했나?

문제 푼 데 걸린 시간은?

시간 복잡도는 ? (잘 모르겠다면 예상)

**Comment by changjun6518** [comment]
[준] - 한 줄로 서기 https://www.acmicpc.net/problem/1138

**Comment by tjwjdgks** [comment]
먼저 올려주셔서 감사합니다~

**Comment by tjwjdgks** [comment]
[Enzo] - 아기 상어 https://www.acmicpc.net/problem/16236

**Comment by protossking** [comment]
[bear] - 랭킹전 대기열 https://www.acmicpc.net/problem/20006

**Comment by ash753** [comment]
[henry] - 상어 초등학교 https://www.acmicpc.net/problem/21608

**Comment by JoongHyuk-Kim** [comment]
[sherlock] - 로봇 청소기 https://www.acmicpc.net/problem/14503

**Comment by BaekKunHee** [comment]
[han] - 윷놀이 https://www.acmicpc.net/problem/2490

**Comment by choiyoungkwon12** [comment]
[ned] - 배열 돌리기 https://www.acmicpc.net/problem/16926

늦게올려서 죄송합니다..
