### ISSUE TITLE
6주차 구현2 2023/2/26(토)

### ISSUE THREAD

**Issue by tjwjdgks** [dk-algorithm/algorithm-study#36]

**Comment by choiyoungkwon12** [comment]
ned - https://www.acmicpc.net/problem/5430

**Comment by JoongHyuk-Kim** [comment]
sherlock - 별찍기19 https://www.acmicpc.net/problem/10994

**Comment by ash753** [comment]
henry - 홀수 홀릭 호석 https://www.acmicpc.net/problem/20164

**Comment by tjwjdgks** [comment]
enzo - 드래곤 커브 https://www.acmicpc.net/problem/15685

**Comment by changjun6518** [comment]
june - 행렬 테두리 회전하기 https://school.programmers.co.kr/learn/courses/30/lessons/77485

**Comment by protossking** [comment]
bear - 스위치 켜고 끄기 https://www.acmicpc.net/problem/1244

**Comment by BaekKunHee** [comment]
han - NBA 농구 https://www.acmicpc.net/problem/2852
