### ISSUE TITLE
2주차 완전탐색 2023/1/29 (일)

### ISSUE THREAD

**Issue by tjwjdgks** [dk-algorithm/algorithm-study#6]
완전탐색 문제 링크 올려주세요

양식
[enzo] <문제 링크>

**Comment by ash753** [comment]
[henry] 종이조각(14391) - https://www.acmicpc.net/problem/14391

**Comment by choiyoungkwon12** [comment]
[ned] 피로도 - https://school.programmers.co.kr/learn/courses/30/lessons/87946?language=java

**Comment by protossking** [comment]
[bear] 숫자야구 -  https://www.acmicpc.net/problem/2503

**Comment by tjwjdgks** [comment]
[enzo] 분해합- https://www.acmicpc.net/problem/2231

**Comment by JoongHyuk-Kim** [comment]
[sherlock] 퇴사 - https://www.acmicpc.net/problem/14501

**Comment by tjwjdgks** [comment]
> [henry] 종이조각(14391) - https://www.acmicpc.net/problem/14391

좋은 문제 인것 같아요

**Comment by changjun6518** [comment]
[june] 괄호 추가하기 - https://www.acmicpc.net/problem/16637

**Comment by BaekKunHee** [comment]
[han] 1,2,3 더하기 - https://www.acmicpc.net/problem/9095

**Comment by choiyoungkwon12** [comment]
> [han] 1,2,3 더하기 - https://www.acmicpc.net/problem/9095

이 문제는 ?!?!?!!! ㅋㅋㅋㅋ
