### ISSUE TITLE
10주차 [자유] 2023/03/24(일)

### ISSUE THREAD

**Issue by changjun6518** [dk-algorithm/algorithm-study#61]
2달 반...!이 지났네요ㅎ.ㅎ

이전 했던 유형 or 풀어봤으면 좋은 유형 중에서 골라주시면 됩니다~

**Comment by tjwjdgks** [comment]
[Enzo] 표현가능한 이진 트리 https://school.programmers.co.kr/learn/courses/30/lessons/150367

**Comment by ash753** [comment]
[henry] 캐슬 디펜스 - https://www.acmicpc.net/problem/17135

**Comment by changjun6518** [comment]
[june] 베스트앨범 - https://school.programmers.co.kr/learn/courses/30/lessons/42579

**Comment by protossking** [comment]
[bear] 토마토 - https://www.acmicpc.net/problem/7576

**Comment by choiyoungkwon12** [comment]
여행경로 - https://school.programmers.co.kr/learn/courses/30/lessons/43164
