### ISSUE TITLE
13주차 [자유] 2023/04/23

### ISSUE THREAD

**Issue by changjun6518** [dk-algorithm/algorithm-study#75]

**Comment by changjun6518** [comment]
요격 시스템 (https://school.programmers.co.kr/learn/courses/30/lessons/181188)

**Comment by ash753** [comment]
henry - 호석이 두 마리 치킨(https://www.acmicpc.net/problem/21278)

**Comment by choiyoungkwon12** [comment]
ned - 게임 맵 최단거리(https://school.programmers.co.kr/learn/courses/30/lessons/1844)

심심해서 sql 도 한문제 던집니다 (https://school.programmers.co.kr/learn/courses/30/lessons/157340)

**Comment by tjwjdgks** [comment]
enzo - 코딩 테스트 공부 ( https://school.programmers.co.kr/learn/courses/30/lessons/118668 )

**Comment by BaekKunHee** [comment]
Han - 전력망을 둘로 나누기 https://school.programmers.co.kr/learn/courses/30/lessons/86971

**Comment by JoongHyuk-Kim** [comment]
sherlock - 치킨배달 https://www.acmicpc.net/problem/15686

**Comment by jerry0339** [comment]
Jerry - 로봇 시뮬레이션 https://www.acmicpc.net/problem/2174
