### ISSUE TITLE
17주차 [자유] 2023/05/28

### ISSUE THREAD

**Issue by changjun6518** [dk-algorithm/algorithm-study#90]

**Comment by changjun6518** [comment]
june - 리코쳇 로봇 https://school.programmers.co.kr/learn/courses/30/lessons/169199

**Comment by choiyoungkwon12** [comment]
ned - 특정한 최단 경로 https://www.acmicpc.net/problem/1504

**Comment by ash753** [comment]
henry - 광고삽입 https://school.programmers.co.kr/learn/courses/30/lessons/72414

**Comment by tjwjdgks** [comment]
enzo - 숫자 타자 대회 ( https://school.programmers.co.kr/learn/courses/30/lessons/136797 )
